CREATE TABLE IF NOT EXISTS LOGIN_STATUS (
    LOGIN_STATUS_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ACCNT_ID INT,
    SESSION_ID VARCHAR(256),
    CURRENT_STATUS VARCHAR(256),
    PASSCODE_HASH VARCHAR(256),
    EXPIRES_AT TIMESTAMP,
    VERSION INT,
    IS_DELETED INT,
    CREATED_BY VARCHAR(128),
    CREATED_AT DATETIME,
    UPDATED_BY VARCHAR(128),
    UPDATED_AT TIMESTAMP,
    UNIQUE (ACCNT_ID, SESSION_ID)
);
