CREATE TABLE IF NOT EXISTS PARTS_ITEM (
    PARTS_ITEM_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ITEM_KEY VARCHAR(256),
    ITEM_QUERY VARCHAR(8192),
    PARTS_IN_PAGE_ID INT,
    ORD_IN_GRP INT,
    VERSION INT,
    IS_DELETED INT,
    CREATED_BY VARCHAR(128),
    CREATED_AT DATETIME,
    UPDATED_BY VARCHAR(128),
    UPDATED_AT TIMESTAMP
);
