CREATE TABLE IF NOT EXISTS GNR_GRP (
    GNR_GRP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    GNR_GRP_NAME VARCHAR(256),
    VERSION INT,
    IS_DELETED INT,
    CREATED_BY VARCHAR(128),
    CREATED_AT DATETIME,
    UPDATED_BY VARCHAR(128),
    UPDATED_AT TIMESTAMP
);
