CREATE TABLE IF NOT EXISTS TBL_DEF (
    TBL_DEF_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TABLE_NAME VARCHAR(256),
    FIELD_NAME VARCHAR(256),
    TYPE_NAME VARCHAR(256),
    ALLOW_NULL VARCHAR(256),
    KEY_DIV VARCHAR(256),
    DEFAULT_VALUE VARCHAR(256),
    EXTRA VARCHAR(256),
    TABLE_LOGICAL_NAME VARCHAR(256),
    FIELD_LOGICAL_NAME VARCHAR(256),
    FOREIGN_TABLE VARCHAR(256),
    DESC_FIELD VARCHAR(256)
);
