CREATE TABLE IF NOT EXISTS ATTR (
    ATTR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ATTR_NAME VARCHAR(256),
    ATTR_VAL VARCHAR(256),
    NUM_MIN INT,
    NUM_MAX INT,
    ATTR_NOTE VARCHAR(256),
    ATTR_GRP_ID INT,
    ORD_IN_GRP INT,
    VERSION INT,
    IS_DELETED INT,
    CREATED_BY VARCHAR(128),
    CREATED_AT DATETIME,
    UPDATED_BY VARCHAR(128),
    UPDATED_AT TIMESTAMP
);
