CREATE TABLE IF NOT EXISTS NTC (
    NTC_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SESSION_ID VARCHAR(256),
    ACCNT_ID INT,
    NOTICE_MSG VARCHAR(256),
    VERSION INT,
    IS_DELETED INT,
    CREATED_BY VARCHAR(128),
    CREATED_AT DATETIME,
    UPDATED_BY VARCHAR(128),
    UPDATED_AT TIMESTAMP
);
