CREATE TABLE IF NOT EXISTS HTML_PARTS (
    HTML_PARTS_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PARTS_NAME VARCHAR(256),
    VERSION INT,
    IS_DELETED INT,
    CREATED_BY VARCHAR(128),
    CREATED_AT DATETIME,
    UPDATED_BY VARCHAR(128),
    UPDATED_AT TIMESTAMP
);
