CREATE TABLE IF NOT EXISTS REQUIRE_APROLE (
    REQUIRE_APROLE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    HTML_PAGE_ID INT,
    APROLE_ID INT,
    VERSION INT,
    IS_DELETED INT,
    CREATED_BY VARCHAR(128),
    CREATED_AT DATETIME,
    UPDATED_BY VARCHAR(128),
    UPDATED_AT TIMESTAMP
);
