CREATE TABLE IF NOT EXISTS SIGN_UP (
    SIGN_UP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    APROLE_ID INT,
    SESSION_ID VARCHAR(256),
    MAIL_ADDRESS VARCHAR(256),
    ACCOUNT_NAME VARCHAR(256),
    PASSWORD_HASH VARCHAR(256),
    PASSCODE_HASH VARCHAR(256),
    FAIL_CNT INT,
    IS_LOCKED INT,
    EXPIRES_AT TIMESTAMP,
    VERSION INT,
    IS_DELETED INT,
    CREATED_BY VARCHAR(128),
    CREATED_AT DATETIME,
    UPDATED_BY VARCHAR(128),
    UPDATED_AT TIMESTAMP,
    UNIQUE (SESSION_ID, MAIL_ADDRESS)
);
