CREATE TABLE IF NOT EXISTS ATTR_IN_ANKEN (
    ATTR_IN_ANKEN_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ANKEN_ID INT,
    ATTR_ID INT,
    VERSION INT,
    IS_DELETED INT,
    CREATED_BY VARCHAR(128),
    CREATED_AT DATETIME,
    UPDATED_BY VARCHAR(128),
    UPDATED_AT TIMESTAMP
);
