CREATE TABLE IF NOT EXISTS URI_PATTERN (
    URI_PATTERN_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    URI_PATTERN_NAME VARCHAR(256),
    URI_PATTERN VARCHAR(256),
    VERSION INT,
    IS_DELETED INT,
    CREATED_BY VARCHAR(128),
    CREATED_AT DATETIME,
    UPDATED_BY VARCHAR(128),
    UPDATED_AT TIMESTAMP
);
