CREATE TABLE IF NOT EXISTS MAIL_ADDR_IN_ACCNT (
    MAIL_ADDR_IN_ACCNT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ACCNT_ID INT,
    MAIL_ADDR VARCHAR(256),
    PASSWORD_ENC VARCHAR(256),
    VERSION INT,
    IS_DELETED INT,
    CREATED_BY VARCHAR(128),
    CREATED_AT DATETIME,
    UPDATED_BY VARCHAR(128),
    UPDATED_AT TIMESTAMP,
    UNIQUE (ACCNT_ID)
);
