CREATE TABLE IF NOT EXISTS SCR_PRM (
    SCR_PRM_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PARAM_KEY VARCHAR(256),
    PARAM_VALUE VARCHAR(256),
    SCR_ID INT,
    ORD_IN_GRP INT,
    VERSION INT,
    IS_DELETED INT,
    CREATED_BY VARCHAR(128),
    CREATED_AT DATETIME,
    UPDATED_BY VARCHAR(128),
    UPDATED_AT TIMESTAMP
);
