CREATE TABLE IF NOT EXISTS SCR_ELM (
    SCR_ELM_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SERVICE_NAME VARCHAR(256),
    ADAPTER VARCHAR(256),
    PREPARE_INPUT VARCHAR(256),
    SCR_ID INT,
    ORD_IN_GRP INT,
    VERSION INT,
    IS_DELETED INT,
    CREATED_BY VARCHAR(128),
    CREATED_AT DATETIME,
    UPDATED_BY VARCHAR(128),
    UPDATED_AT TIMESTAMP
);
