CREATE TABLE IF NOT EXISTS HTML_PARTS_IN_APROLE (
    HTML_PARTS_IN_APROLE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    APROLE_ID INT,
    HTML_PARTS_ID INT,
    AUTH_KIND VARCHAR(256),
    VERSION INT,
    IS_DELETED INT,
    CREATED_BY VARCHAR(128),
    CREATED_AT DATETIME,
    UPDATED_BY VARCHAR(128),
    UPDATED_AT TIMESTAMP
);
