CREATE TABLE IF NOT EXISTS LNK (
    LNK_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    LNK_NAME VARCHAR(256),
    URI_PATTERN_ID INT,
    IS_POST INT,
    LNK_GRP_ID INT,
    ORD_IN_GRP INT,
    VERSION INT,
    IS_DELETED INT,
    CREATED_BY VARCHAR(128),
    CREATED_AT DATETIME,
    UPDATED_BY VARCHAR(128),
    UPDATED_AT TIMESTAMP
);
