CREATE TABLE IF NOT EXISTS ACCNT (
    ACCNT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ACCOUNT_NAME VARCHAR(256),
    MAIL_ADDRESS VARCHAR(256),
    PASSWORD VARCHAR(256),
    VERSION INT,
    IS_DELETED INT,
    CREATED_BY VARCHAR(128),
    CREATED_AT DATETIME,
    UPDATED_BY VARCHAR(128),
    UPDATED_AT TIMESTAMP,
    UNIQUE (MAIL_ADDRESS)
);
