CREATE TABLE IF NOT EXISTS APROLE (
    APROLE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ROLE_NAME VARCHAR(256),
    VERSION INT,
    IS_DELETED INT,
    CREATED_BY VARCHAR(128),
    CREATED_AT DATETIME,
    UPDATED_BY VARCHAR(128),
    UPDATED_AT TIMESTAMP
);
