CREATE TABLE IF NOT EXISTS GNR_KEY_VAL (
    GNR_KEY_VAL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    GNR_KEY VARCHAR(256),
    GNR_VAL VARCHAR(256),
    GNR_GRP_ID INT,
    ORD_IN_GRP INT,
    VERSION INT,
    IS_DELETED INT,
    CREATED_BY VARCHAR(128),
    CREATED_AT DATETIME,
    UPDATED_BY VARCHAR(128),
    UPDATED_AT TIMESTAMP
);
