CREATE TABLE IF NOT EXISTS PARTS_IN_PAGE (
    PARTS_IN_PAGE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    HTML_PAGE_ID INT,
    HTML_PARTS_ID INT,
    ORD_IN_GRP INT,
    VERSION INT,
    IS_DELETED INT,
    CREATED_BY VARCHAR(128),
    CREATED_AT DATETIME,
    UPDATED_BY VARCHAR(128),
    UPDATED_AT TIMESTAMP
);
