CREATE TABLE IF NOT EXISTS ACCNT_AUTH_LOCK (
    ACCNT_AUTH_LOCK_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ACCNT_ID INT,
    FAIL_CNT INT,
    LOCKED_UNTIL TIMESTAMP,
    VERSION INT,
    IS_DELETED INT,
    CREATED_BY VARCHAR(128),
    CREATED_AT DATETIME,
    UPDATED_BY VARCHAR(128),
    UPDATED_AT TIMESTAMP,
    UNIQUE (ACCNT_ID)
);
